### ISSUE TITLE
`gimlet gitops bootstrap` to support branches other than `main`

### ISSUE THREAD

**Issue by laszlocph** [gimlet-io/gimlet-cli#10]
Today `gimlet gitops bootstrap` assumes the `main` branch that needs to be synced to the cluster.

It puts a 

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gitops-repo
  namespace: flux-system
spec:
  interval: 15s
  ref:
    branch: main
  secretRef:
    name: gitops-repo
  url: ssh://git@github.com/<user>/<repo>
```

to the gitops repo.

The branch name should come from the current git branch. I had `master` in an old gitops repo.
