### ISSUE TITLE
Gimlet manifest to accept kustomize style patches

### ISSUE THREAD

**Issue by laszlocph** [gimlet-io/gimlet-cli#31]
Can be used as an escape hatch

**Comment by laszlocph** [comment]
We decided that we handle the kustomize patching inside Gimlet.

This way `gimlet manifest template` and the release automation in GimletD will to the exact same thing. We will not send the kustomize patches downstream for Flux (or manual kubectl apply -k) to handle.

**Comment by laszlocph** [comment]
The remaining tasks here:

- [ ] Finish support for Json6902Patches

The model has it already: https://github.com/gimlet-io/gimletd/blob/main/dx/manifest.go#L23
Probably not more difficult than this: https://github.com/gimlet-io/gimlet-cli/blob/main/commands/manifest/template.go#L93
Implement it in GimletD too: https://github.com/gimlet-io/gimletd/blob/main/worker/gitops.go#L645
Possibly make the code DRY

**Comment by laszlocph** [comment]
Json patches format is the following:

```
app: myapp
env: staging
namespace: my-team
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.32.0
values:
  replicas: 10
  ingress:
    host: myapp.staging.mycompany.com
    tlsEnabled: true
json6902Patches:
- target:
    group: "networking.k8s.io"
    version: "v1"
    kind: "Ingress"
    name: "myapp"
  patch: |
    ---
    - op: replace
      path: /spec/rules/0/host
      value: myapp.com
    - op: replace
      path: /spec/tls/0/hosts/0
      value: myapp.com
```

as seen in the unit tests: https://github.com/gimlet-io/gimlet-cli/blob/main/commands/manifest/template_test.go#L95
