### ISSUE TITLE
Add auto build cancel to the Github Actions workflow

### ISSUE THREAD

**Issue by laszlocph** [gimlet-io/gimlet-cli#49]
https://github.com/styfle/cancel-workflow-action

as the first step on the build / tip / publish flows

```
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
```
